# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd765b7e0932ad6bea415dd857fe707df0885261c063e14cc161d2423a49cf5fb2affebe80541c8d083fa04a9b72a399f3b77747d5a46049e51fffe44873838

test:
  secret_key_base: 9d0a927a089a2c9f399ce0cb9186dca69b6d31297740e659ee15a791ced8ee875474c9c79ef4415551d816c390efd01f555612ba156b682c435ed93ce922e68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
